### ISSUE TITLE
Abort on grayscale images

### ISSUE THREAD

**Issue by vit1251** [AbdoulMa/copycolors#1]
During execution on attach image got panic:

```
$ copycolors nmbjQxU0iZs.png 
thread 'main' panicked at 'internal error: entered unreachable code', src/image_trait.rs:17:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

![nmbjQxU0iZs](https://github.com/AbdoulMa/copycolors/assets/110534/b06b8efe-b1b6-4004-a0a0-3d7e7afe658b)

Expected:

![image](https://github.com/AbdoulMa/copycolors/assets/110534/5e1cba5e-b85f-4fb8-98fb-b074bb55cbd1)

**Comment by vit1251** [comment]
Yet another one image:

![tori-torii-shrine-b-w](https://github.com/AbdoulMa/copycolors/assets/110534/d9be17e4-c3e7-4a15-98c7-e794c3efd853)

Expected:

![image](https://github.com/AbdoulMa/copycolors/assets/110534/ae6d0f07-6178-407d-b76b-c440df8689de)

**Comment by AbdoulMa** [comment]
Thanks for reporting the problem. I will try to fix it next week and let you know.

**Comment by AbdoulMa** [comment]
After debugging, it appears that images from which you are trying to extract dominant colors have pixels with L8  type colors,  which is not supported by the extraction algorithm. 
I released a fixed version of the program to better explain the problem to the command users.
I will try to find a solution for this kind of images in the next days. 
Thanks.
